language: r
r: bioc-devel

r_github_packages:
  - rstudio/bookdown
  - rstudio/packrat

addons:
  apt:
    packages:
      - libgsl-dev

install:
  - R -e "0" --args --boostrap-packrat

cache:
  directories:
  - $TRAVIS_BUILD_DIR/docs
  - $TRAVIS_BUILD_DIR/_bookdown_files
  - $TRAVIS_BUILD_DIR/packrat/src
  - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

env:
  global:
    - secure: "DcwDp+3JywIavoRg/E2Q4CYKLDc7V9Wg6FZBOBKzFq3Reov3Q4qYCrGjpj+jBg3Mq1K91dSve2KLKvQtQu3Ejv1tT25y8+G+bQ+5FKNZzYpuOAmTp1l2VcEBTe0a7DgZDXz5j1+QbUXmajoV9irBrIFw7CmWhwejiVnyi4K9BRQLUeeC1y2TC9E1+eXGxKKvmgYzGO55SnG6LHNb0nIYqkkNNW+IF67fegIhByYjYKLPhqDj1ONHtXETsuQBJljCA8a1awXSZhzBpB+2Dzj/2SDS5scPh/HZh/LeK5tPDzHI/+isadwhq8CjuI0L23UBG+gwAP8mvUuQf/eTNEq2bCqmGRS6XLvvIXc6AQ458Zf2ftMEcJkYrXQDl39AOT/4wlRn/ojIkKtwOY7Xi2rKuRcjziny/EOudFF37TjWFK6LGrViXuTJGF1EOx61y51RfmSkcApdy7clSFlhr9q3qRHuAWXlEua7Gy+XusPUL/ow/zqM7gbsZSNJ+gm8fTcrFHKP1Yysp8q0fK+dMFhOx0HXPQMBwwzimitrKQ2H75UBRcbrlcrVNUmIhKoMAde/f9CCrACYTWYD3rzjBFNT3F99YYyghkv6OiaEymQQXPu58cGFWXFOFZMRDJXMiKMOpNHr9txVcnDWxOxVBDNt3arFp5dLBs1hkoAdXAW4iLg="
